In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv('BitcoinPrice.csv')

In [3]:
data.head()

Date        Price
0  2018-08-25 00:00:00  6719.429231
1  2018-08-26 00:00:00  6673.274167
2  2018-08-27 00:00:00  6719.266154
3  2018-08-28 00:00:00  7000.040000
4  2018-08-29 00:00:00  7054.276429

In [4]:
data.tail()

Date         Price
360  2019-08-20 00:00:00  10746.507692
361  2019-08-21 00:00:00  10169.094167
362  2019-08-22 00:00:00  10030.746667
363  2019-08-23 00:00:00  10255.977500
364  2019-08-24 00:00:00  10158.540833

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    365 non-null    object 
 1   Price   365 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.8+ KB


In [7]:
data.drop(['Date'],1,inplace=True)

In [8]:
data.head()

Price
0  6719.429231
1  6673.274167
2  6719.266154
3  7000.040000
4  7054.276429

In [ ]:
#finding predcition for nect 30 days

In [9]:
p_days=30                                                   #assigning no of days (30) to a variable and making a new col
data['prediction']=data[['Price']].shift(-p_days)           #prediction to get the next 30 day 

In [10]:
data.head()

Price   prediction
0  6719.429231  6639.304167
1  6673.274167  6412.459167
2  6719.266154  6468.631667
3  7000.040000  6535.476667
4  7054.276429  6677.342500

In [11]:
data.tail

<bound method NDFrame.tail of             Price   prediction
0     6719.429231  6639.304167
1     6673.274167  6412.459167
2     6719.266154  6468.631667
3     7000.040000  6535.476667
4     7054.276429  6677.342500
..            ...          ...
360  10746.507692          NaN
361  10169.094167          NaN
362  10030.746667          NaN
363  10255.977500          NaN
364  10158.540833          NaN

[365 rows x 2 columns]>

In [ ]:
#NaN stands for null values ,so droping it

In [ ]:
#separate x and y

In [ ]:
#creating x array

In [13]:
x=np.array(data.drop(['prediction'],1))

In [14]:
x=x[:len(data)-p_days]

In [15]:
x

array([[ 6719.42923077],
       [ 6673.27416667],
       [ 6719.26615385],
       [ 7000.04      ],
       [ 7054.27642857],
       [ 6932.6625    ],
       [ 6981.94615385],
       [ 7100.94666667],
       [ 7247.93538462],
       [ 7260.94923077],
       [ 7326.8525    ],
       [ 7113.06923077],
       [ 6433.27166667],
       [ 6444.80416667],
       [ 6366.1075    ],
       [ 6286.42583333],
       [ 6297.87769231],
       [ 6296.32083333],
       [ 6273.1375    ],
       [ 6450.17923077],
       [ 6499.0625    ],
       [ 6518.655     ],
       [ 6480.64416667],
       [ 6400.60083333],
       [ 6296.63166667],
       [ 6335.82666667],
       [ 6418.56266667],
       [ 6669.99083333],
       [ 6709.3125    ],
       [ 6710.445     ],
       [ 6639.30416667],
       [ 6412.45916667],
       [ 6468.63166667],
       [ 6535.47666667],
       [ 6677.3425    ],
       [ 6550.47416667],
       [ 6593.135     ],
       [ 6590.96833333],
       [ 6562.64166667],
       [ 6470.4025    ],


In [ ]:
#creating y array

In [16]:
y=np.array(data['prediction'])

In [19]:
y=y[: -p_days]

In [20]:
y

array([ 6639.30416667,  6412.45916667,  6468.63166667,  6535.47666667,
        6677.3425    ,  6550.47416667,  6593.135     ,  6590.96833333,
        6562.64166667,  6470.4025    ,  6563.62833333,  6568.54916667,
        6581.48666667,  6558.5375    ,  6618.56769231,  6621.71166667,
        6563.00916667,  6248.63583333,  6260.53083333,  6260.64583333,
        6299.39916667,  6452.57166667,  6596.61833333,  6596.27615385,
        6568.04076923,  6487.44416667,  6488.82583333,  6531.60166667,
        6498.48583333,  6481.426     ,  6508.31      ,  6478.0825    ,
        6473.75333333,  6465.9175    ,  6448.22166667,  6382.66833333,
        6309.45285714,  6310.28416667,  6342.28083333,  6387.67416667,
        6363.79583333,  6391.87333333,  6436.965     ,  6445.35416667,
        6538.79      ,  6486.25166667,  6411.28083333,  6399.03333333,
        6378.26833333,  6401.93666667,  6372.06333333,  6176.155     ,
        5615.18      ,  5596.1925    ,  5558.24333333,  5606.04416667,
      

In [ ]:
#split into train and test data

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [25]:
p_day_array=np.array(data.drop(['prediction'],1))[-p_days :]

In [26]:
p_day_array

array([[ 9774.2575    ],
       [ 9725.4025    ],
       [ 9500.32416667],
       [ 9533.97933333],
       [ 9539.7125    ],
       [ 9873.81166667],
       [10088.8       ],
       [10478.90166667],
       [10790.63      ],
       [10826.275     ],
       [11713.16166667],
       [11759.01916667],
       [11703.73833333],
       [11803.88833333],
       [11816.9125    ],
       [11586.1725    ],
       [11377.80416667],
       [11397.80166667],
       [11144.38916667],
       [10450.81333333],
       [ 9988.9475    ],
       [10230.73333333],
       [10292.38333333],
       [10295.1175    ],
       [10605.82583333],
       [10746.50769231],
       [10169.09416667],
       [10030.74666667],
       [10255.9775    ],
       [10158.54083333]])

In [ ]:
#estimation

In [27]:
from sklearn.ensemble import RandomForestRegressor

In [28]:
Rf=RandomForestRegressor(n_estimators=1000,random_state=1)

In [29]:
Rf.fit(x_train,y_train)

RandomForestRegressor(n_estimators=1000, random_state=1)

In [35]:
print('Random Forest Accuracy: {:.2f}%'.format(Rf.score(x_test,y_test)*100))

Random Forest Accuracy: 78.28%


In [ ]:
#PREDICTION

In [37]:
Rf_pred=Rf.predict(x_test)

In [38]:
Rf_pred

array([11069.77037404, 11448.69755532, 10359.26768513,  3898.99443692,
        4429.00981681,  5226.1070525 , 10252.3400375 ,  3936.14493679,
        3712.31220045,  8263.02777712,  4207.70565333,  3685.08188494,
        4417.20373667,  3733.05757577,  6317.55457833,  6330.40666167,
       10128.81565558,  5153.54102455,  3849.59351462,  3708.15177019,
       12156.77837878,  6285.0001    ,  6545.58181167, 11451.44371365,
        4563.63617404,  8113.78624333,  4584.6158    ,  4042.88016   ,
        6430.98931717, 10076.18029583,  3873.79813173, 10431.38158263,
        3999.85552583,  6137.36668519,  6673.39418417, 10240.31662615,
        5847.58794917,  5117.67450583,  6595.09223   ,  3893.52156917,
        6613.20926083,  6680.38798994, 10359.26768513,  3672.82448833,
        6388.53555917,  3971.19815451,  3835.61621538,  3738.9124525 ,
        4032.39609205, 11151.78733083,  4107.9175925 ,  3633.86396141,
        6478.1193069 ,  5116.9349125 ,  4199.8080275 ,  4561.5148375 ,
      

In [39]:
y_test

array([11342.3175    , 12686.38833333, 10605.82583333,  3998.4975    ,
        4011.36583333,  5305.275     , 11816.9125    ,  3426.19      ,
        3880.7675    ,  8543.03      ,  3920.53666667,  3645.27666667,
        6596.61833333,  5214.27666667,  6568.04076923,  7817.76833333,
       10088.8       ,  4026.63583333,  6618.56769231,  5126.83416667,
       11779.45083333,  3392.405     ,  9096.28583333, 10438.55416667,
        3589.26083333,  8646.195     ,  6452.57166667,  3454.00882353,
        6531.60166667, 10292.38333333,  3994.34833333, 10300.41166667,
        4035.855     ,  3528.80333333,  5633.7475    ,  9584.47583333,
        6391.87333333,  5109.94666667,  9227.125     ,  3632.395     ,
        6535.47666667,  7979.575     ,  9873.81166667,  3403.96416667,
        6378.26833333,  4109.31666667,  3883.98928571,  3905.05833333,
        4167.54666667,  9346.0725    ,  6487.44416667,  3452.32833333,
        6508.31      ,  5527.80166667,  3579.89666667,  6299.39916667,
      

In [ ]:
#ORIGINAL VALUES FOR 30 DAYS BITCOIN PREDDICTION

In [40]:
data.head()

Price   prediction
0  6719.429231  6639.304167
1  6673.274167  6412.459167
2  6719.266154  6468.631667
3  7000.040000  6535.476667
4  7054.276429  6677.342500

In [41]:
data.tail()

Price  prediction
360  10746.507692         NaN
361  10169.094167         NaN
362  10030.746667         NaN
363  10255.977500         NaN
364  10158.540833         NaN

In [42]:
data.head(30)

Price   prediction
0   6719.429231  6639.304167
1   6673.274167  6412.459167
2   6719.266154  6468.631667
3   7000.040000  6535.476667
4   7054.276429  6677.342500
5   6932.662500  6550.474167
6   6981.946154  6593.135000
7   7100.946667  6590.968333
8   7247.935385  6562.641667
9   7260.949231  6470.402500
10  7326.852500  6563.628333
11  7113.069231  6568.549167
12  6433.271667  6581.486667
13  6444.804167  6558.537500
14  6366.107500  6618.567692
15  6286.425833  6621.711667
16  6297.877692  6563.009167
17  6296.320833  6248.635833
18  6273.137500  6260.530833
19  6450.179231  6260.645833
20  6499.062500  6299.399167
21  6518.655000  6452.571667
22  6480.644167  6596.618333
23  6400.600833  6596.276154
24  6296.631667  6568.040769
25  6335.826667  6487.444167
26  6418.562667  6488.825833
27  6669.990833  6531.601667
28  6709.312500  6498.485833
29  6710.445000  6481.426000